name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.34'
          - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Perl Environment
        uses: shogo82148/actions-setup-perl@v1.16.1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: Perl Version
        run: perl -V
      - name: Run Tests
        run: |
          cpanm --notest --installdeps -v .
          cpanm --test-only -v .
