name: linux
on:
  - push
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        # - '5.8'
        # - '5.10'
        # - '5.12'
        # - '5.14'
        # - '5.16'
        # - '5.18'
        # - '5.20'
        # - '5.22'
        # - '5.24'
        # - '5.26'
        # - '5.28'
        # - '5.30'
        # - '5.32'
          - '5.34'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Perl
      - uses: shogo82148/actions-setup-perl@1.16.1
        with:
          perl-version: ${{ matrix.perl-version }}
      - name: Perl Version
        run: perl -V
      - name: Install Dependencies
        run: cpanm --installdeps .
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: |
          prove -lr -l -b -I inc t