name: Perl Matrix Testing
on:
  - push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        perl: [ '5.34', '5.32' ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1.16.2
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - run: perl -V
      - run: cpanm --installdeps .
      - run: prove -lv t
